function [x_next,f_next]=Wolfe__Search(f_test,g_test,x_current,d_current)
%==========================================================================
%函数调用格式：
%[x_next,f_next]=Wolfe__Search(f_test,g_test,x_current,d_current)
%--------------------------------------------------------------------------
%输入参数说明
%--------------------------------------------------------------------------
%f_test：目标函数
%g_test：目标函数对变量x的导数
%x_current：x在向量空间中的当前点（已确定）
%d_current：f_test在x_current的下降搜索方向（已确定）
%rho=0.1：可接受系数，0<rho<1
%sigma=0.11:可接受点处的切线斜率大于初始点处切线斜率的倍数，0<rho<sigma<1
%如果||d_current||<1.e-6，无法进行搜索，迭代终止
%--------------------------------------------------------------------------
%输出参数
%--------------------------------------------------------------------------
%alpha_acceptable：由Wolfe搜索获得的可接受步长
%x_next：x_next=x_current+alpha_acceptable*d_current
%f_next：对应于x_next的函数值
%k：完成Wolfe搜索所需的迭代次数
%==========================================================================
%==========================================================================
%主程序及说明
%--------------------------------------------------------------------------
%在调用本程序的上级程序中定义f_test和g_test的表达式
%alpha_k:经过k次Wolfe搜索后，获得的步长值
%alpha_k_temp:临时存储alpha_k，旧的alpha_k在程序中还要保留用于赋值
%alpha_lower_k：在[alpha_lower_k,alpha_k]使用两点外插公式II，alpha_k的下限
%alpha_upper_k：在[alpha_lower_k,alpha_k]使用两点内插公式I，alpha_k的上限
%alpha_lower_k的初值设为0
%alpha_upper_k的初值为alpha_initial
%f_current：f_test在x_current处的函数值
%g_current：g_test在x_current处的函数值
%f_alpha_lower_k：f_test在x_lower_k处的函数值
%g_alpha_lower_k：g_test在x_lower_k处的函数t
%df_alpha_lower_k：f_test对alpha的导数在x_lower_k处的函数值
%x_alpha_k=x_current+alpha_k*d_current
%f_alpha_k：f_test在x_alpha_k处的函数值
%g_alpha_k：g_test在x_alpha_k处的函数值
%df_alpha_k：f_test对alpha的导数在x_alpha_k处的函数值
%k_max：最大迭代次数，防止程序陷入循环而设置，在这里设为1000
%--------------------------------------------------------------------------
rho=0.1;
sigma=0.11;
k_max=1000;%1000
k=0;

f_current=f_test(x_current);
g_current=g_test(x_current);
f_alpha_lower_k=f_current;
%alpha_lower_k初值为0，此时f_alpha_lower_k等于f_current
g_alpha_lower_k=g_current;
df_alpha_lower_k=(d_current')*g_alpha_lower_k;
f_alpha_lower_0=f_alpha_lower_k;
df_alpha_lower_0=df_alpha_lower_k;
%--------------------------------------------------------------------------
%估计alpha_initial的值，并防止alpha_initial过大或过小
%--------------------------------------------------------------------------
tolerance=1e-15;
if(abs(df_alpha_lower_k)>tolerance)
    alpha_initial=-2*f_alpha_lower_k/df_alpha_lower_k;
else
    alpha_initial=1;
end
if(alpha_initial<tolerance)
     alpha_initial=1;
end
alpha_lower_k=0;
alpha_upper_k=1e8;
alpha_k=alpha_initial;
%--------------------------------------------------------------------------
%开始Wolfe非精确插值搜索
%--------------------------------------------------------------------------
for k=1:k_max
    x_alpha_k=x_current+alpha_k*d_current;
    f_alpha_k=f_test(x_alpha_k);
    g_alpha_k=g_test(x_alpha_k);
    df_alpha_k=(d_current')*g_alpha_k;
    Wolfe_condition1=f_alpha_k-f_alpha_lower_0-rho*alpha_k*df_alpha_lower_0;
    %即Armijo条件
    Wolfe_condition2=sigma*df_alpha_lower_0-df_alpha_k;
    if(Wolfe_condition1<=0)
        if(Wolfe_condition2<=0)
        %Wolfe_condition1和Wolfe_condition2都满足
        alpha_acceptable=alpha_k;
        x_next=x_alpha_k;
        f_next=f_alpha_k;
        
        break;
        else
           %仅 Wolfe_condition1满足，对alpha_lower_k和alpha_k两点外插公式II
            delta_alpha_k=(alpha_k-alpha_lower_k)*df_alpha_k/(df_alpha_lower_k-df_alpha_k);
            if(delta_alpha_k<=0)
                alpha_k_temp=2*alpha_k;
                %外插特殊情况处理
            else
                alpha_k_temp=alpha_k+delta_alpha_k;
            end
            alpha_lower_k=alpha_k;%更新可接受步长的下边界
            f_alpha_lower_k=f_alpha_k;
            df_alpha_lower_k=df_alpha_k;
            alpha_k=alpha_k_temp;
        end
    else %Wolfe_condition1不满足，对alpha_lower_k和alpha_k两点内插公式I
        if(alpha_k<alpha_upper_k)
            alpha_upper_k=alpha_k;%更新可接受步长的上边界
        end
        alpha_k_temp=alpha_lower_k+(1/2)*(((alpha_k-alpha_lower_k)^2)*df_alpha_lower_k)/(f_alpha_lower_k-f_alpha_k+(alpha_k-alpha_lower_k)*df_alpha_lower_k);
        alpha_k=alpha_k_temp;
    end
    if(alpha_upper_k-alpha_lower_k<tolerance)
        %防止在过小区间内搜索
        alpha_acceptable=alpha_k;
        x_next=x_alpha_k;
        f_next=f_alpha_k;
        break;
    end
end
if(Wolfe_condition1>0)||(Wolfe_condition2>0)
    %disp('Wolfe inexact line search algorithm failed');
    %经过k_max次搜索后未找到可接受的步长
    %alpha_acceptable=NaN;
   % x_next=NaN;
    %f_next=NaN;
    %经过k_max次搜索后未找到可接受的步长,取alpha_acceptable=0
    alpha_acceptable=0;
    x_next=x_current;
    f_next=f_test(x_current);
end

end
%==========================================================================

